version: 1.0.{build}
image: ubuntu
services:
- docker
branches:
    only:
    - master
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish -c Release -o out
- docker FROM microsoft/aspnetcore:2.0
- docker WORKDIR /app
- docker COPY --from=out .
- docker ENTRYPOINT ["dotnet", "HealthAPI.dll"]
artifacts:
- path: publish\*.zip
  name: mypackage
  type: WebDeployPackage  
deploy:
  provider: S3
  access_key_id: 
    secure: s5pnr2vdvrNNVyoNltgAgGhnm4gVGgVYFMcaK21Tfhw=
  secret_access_key:
    secure: ZgEoIvDRFbURZ4qXfwusxwnnIWlmggVT6Ocf0waaZaw/e6rbzyXt2tClmshjONLl
  bucket: health.api.bucket
  region: eu-west-1
  unzip: false
  set_public: false
  folder: publish
  artifact: HealthAPI.zip