version: 1.0.{build}
environment:
  HealthDbConnectionString:
    secure: 4Qb2yNR0MhzSVLQu0YLCROq2+yoLbpPCnCYnpgJV5uFANx4bi9f0WBA0IRTCN8cw5/7a4/x8t16mmzV6TY7JyUoQI0X80J76bXbBYLINTKZKfY67oxj7hPjdbA5yXBG3buNP4XgI32A80dbywhowFIPrZoAA8RyZJiglbMsPyO6p9rl/8s0XmmjhSL1ll5S9Yllu3+BDGHJSZ+xUwuYBDjHUCo0kWLG3jdGISA1gn6yFMtw7VJV0ZVsnrq3ObqGvzqCqama364ALUjyY0BhBNLNL9Qvefo04IH2n+RW8nd4CgwAdCr+PkAbtp2bu+R/A
image: Visual Studio 2017 Preview
branches:
    only:
    - master
before_build:
- cmd: >-

    dotnet restore ./src/Health.API.Tests.Unit/Health.API.Tests.Unit.csproj

    dotnet restore ./src/Repository.Tests.Unit/Repository.Tests.Unit.csproj

    dotnet restore ./src/Services.Tests.Unit/Services.Tests.Unit.csproj
    
    dotnet restore ./src/Utils.Tests.Unit/Utils.Tests.Unit.csproj

    dotnet restore ./src/Health.API/Health.API.csproj
    
    dotnet restore ./src/Repositories/Repositories.csproj

    dotnet restore ./src/Services/Services.csproj

    dotnet restore ./src/Utils/Utils.csproj
    
    dotnet restore ./src/Importer.Fitbit/Fitbit.csproj
    
    dotnet restore ./src/Importer.Fitbit.Tests.Unit/Importer.Fitbit.Tests.Unit.csproj
    
    dotnet restore ./src/Importer.Withings.Tests.Unit/Importer.Withings.Tests.Unit.csproj
    
    dotnet restore ./src/Importer.GoogleSheets.Tests.Unit/Importer.GoogleSheets.Tests.Unit.csproj

    
    dotnet clean ./src/Health.API.Tests.Unit/Health.API.Tests.Unit.csproj

    dotnet clean ./src/Repository.Tests.Unit/Repository.Tests.Unit.csproj

    dotnet clean ./src/Services.Tests.Unit/Services.Tests.Unit.csproj
    
    dotnet clean ./src/Utils.Tests.Unit/Utils.Tests.Unit.csproj

    dotnet clean ./src/Health.API/Health.API.csproj
    
    dotnet clean ./src/Repositories/Repositories.csproj

    dotnet clean ./src/Services/Services.csproj

    dotnet clean ./src/Utils/Utils.csproj
    
    dotnet clean ./src/Importer.Fitbit/Fitbit.csproj
	
    dotnet clean ./src/Importer.Fitbit.Tests.Unit/Importer.Fitbit.Tests.Unit.csproj
    
    dotnet clean ./src/Importer.Withings.Tests.Unit/Importer.Withings.Tests.Unit.csproj
    
    dotnet clean ./src/Importer.GoogleSheets.Tests.Unit/Importer.GoogleSheets.Tests.Unit.csproj


build:
  project: Health.API.sln
  publish_wap: true
  verbosity: minimal
test: auto
after_test:
- cmd: dotnet publish ./src/Health.API /p:OutDir="%appveyor_build_folder%\publish" /p:PackageLocation="%appveyor_build_folder%\publish" /p:PublishProfile=Release /p:WebPublishMethod=Package
artifacts:
- path: publish\*.zip
  name: mypackage
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://musgrosoft-health-api.scm.azurewebsites.net:443/msdeploy.axd?site=Musgrosoft-Health-API
  website: Musgrosoft-Health-API
  username: $Musgrosoft-Health-API
  password:
    secure: Gz5GqhViaz2dZNJtBcfiXUptmuRRaS8YAZBWaqXhGRDKmqu70kTVdj65zvJnDzAM16M16iSL6vhji1Li7DakMA==
  artifact: mypackage
  aspnet_core: true
  remove_files: true
  app_offline: true
  aspnet_core_force_restart: true