version: 1.0.{build}
environment:
  HealthDbConnectionString:
    secure: 4Qb2yNR0MhzSVLQu0YLCROq2+yoLbpPCnCYnpgJV5uFANx4bi9f0WBA0IRTCN8cw5/7a4/x8t16mmzV6TY7JyUoQI0X80J76bXbBYLINTKZKfY67oxj7hPjdbA5yXBG3buNP4XgI32A80dbywhowFIPrZoAA8RyZJiglbMsPyO6p9rl/8s0XmmjhSL1ll5S9Yllu3+BDGHJSZ+xUwuYBDjHUCo0kWLG3jdGISA1gn6yFMtw7VJV0ZVsnrq3ObqGvzqCqama364ALUjyY0BhBNLNL9Qvefo04IH2n+RW8nd4CgwAdCr+PkAbtp2bu+R/A
image: Visual Studio 2019
branches:
    only:
    - master
before_build:
- ps: nuget restore 
build:
  project: Health.API.sln
  publish_wap: true
  verbosity: minimal
test: auto
after_test:
- cmd: dotnet publish ./src/Health.API /p:OutDir="%appveyor_build_folder%\publish" /p:PackageLocation="%appveyor_build_folder%\publish" /p:PublishProfile=Release /p:WebPublishMethod=Package
artifacts:
- path: publish\*.zip
  name: mypackage
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://musgrosoft-health-api.scm.azurewebsites.net:443/msdeploy.axd?site=Musgrosoft-Health-API
  website: musgrosoft-health-api
  username: $musgrosoft-health-api
  password:
    secure: c503wsToyVTemEHSwk9RGYnPUy5R+gxx9LAQagGCobSn24D6/ByK4JUBHXwiz4JnJLLGlixJ5qFkwfINL8HAoQ==
  artifact: mypackage
  aspnet_core: true
  remove_files: true
  app_offline: true
  aspnet_core_force_restart: true