version: 1.0.{build}
image: ubuntu
services:
- docker
branches:
    only:
    - master
build:
  project: Health.API.sln
  verbosity: minimal
after_build:
- sh: dotnet publish -c Release -o out
- docker build -t healthapi .
- docker run -d -p 8080:80 --name myapp healthapi
test: auto
after_test:
