version: 1.0.{build}
image: ubuntu
services:
- docker
branches:
    only:
    - master
build:
  verbosity: minimal
after_test:
- cmd: dotnet publish -c Release -o C:\out
- docker build -t healthapi .
- docker cp C:/out/. healthapi:/app
- docker run -d -p 8080:80 --name myapp healthapi