version: 1.0.{build}
environment:
  HealthDbConnectionString:
    secure: 4Qb2yNR0MhzSVLQu0YLCROq2+yoLbpPCnCYnpgJV5uFANx4bi9f0WBA0IRTCN8cw5/7a4/x8t16mmzV6TY7JyUoQI0X80J76bXbBYLINTKZKfY67oxj7hPjdbA5yXBG3buNP4XgI32A80dbywhowFIPrZoAA8RyZJiglbMsPyO6p9rl/8s0XmmjhSL1ll5S9Yllu3+BDGHJSZ+xUwuYBDjHUCo0kWLG3jdGISA1gn6yFMtw7VJV0ZVsnrq3ObqGvzqCqama364ALUjyY0BhBNLNL9Qvefo04IH2n+RW8nd4CgwAdCr+PkAbtp2bu+R/A
image: Visual Studio 2017 Preview
branches:
    only:
    - master
before_build:
- cmd: >-

    dotnet restore ./src/HealthAPI.Acceptance.Tests/HealthAPI.Acceptance.Tests.csproj

    dotnet restore ./src/HealthAPI.Unit.Tests/HealthAPI.Unit.Tests.csproj

    dotnet restore ./src/Migrators.Unit.Tests/Migrators.Unit.Tests.csproj

    dotnet restore ./src/Repository.Unit.Tests/Repository.Unit.Tests.csproj

    dotnet restore ./src/Services.Tests/Services.Tests.csproj
    
    dotnet restore ./src/Utils.Unit.Tests/Utils.Unit.Tests.csproj

    dotnet restore ./src/HealthAPI/HealthAPI.csproj

    dotnet restore ./src/Fitbit/Fitbit.csproj
    
    dotnet restore ./src/Nokia/Nokia.csproj
    
    dotnet restore ./src/Google/Google.csproj

    dotnet restore ./src/Repositories/Repositories.csproj

    dotnet restore ./src/Services/Services.csproj

    dotnet restore ./src/Utils/Utils.csproj
    
    dotnet restore ./src/Fitbit.Unit.Tests/Fitbit.Unit.Tests.csproj
    
    dotnet restore ./src/Nokia.Unit.Tests/Nokia.Unit.Tests.csproj
    
    dotnet restore ./src/GoogleSheets.Unit.Tests/GoogleSheets.Unit.Tests.csproj


    dotnet clean ./src/HealthAPI.Acceptance.Tests/HealthAPI.Acceptance.Tests.csproj
    
    dotnet clean ./src/HealthAPI.Unit.Tests/HealthAPI.Unit.Tests.csproj

    dotnet clean ./src/Migrators.Unit.Tests/Migrators.Unit.Tests.csproj

    dotnet clean ./src/Repository.Unit.Tests/Repository.Unit.Tests.csproj

    dotnet clean ./src/Services.Tests/Services.Tests.csproj
    
    dotnet clean ./src/Utils.Unit.Tests/Utils.Unit.Tests.csproj

    dotnet clean ./src/HealthAPI/HealthAPI.csproj

    dotnet clean ./src/Fitbit/Fitbit.csproj
    
    dotnet clean ./src/Nokia/Nokia.csproj
    
    dotnet clean ./src/Google/Google.csproj

    dotnet clean ./src/Repositories/Repositories.csproj

    dotnet clean ./src/Services/Services.csproj

    dotnet clean ./src/Utils/Utils.csproj
    
    dotnet clean ./src/Fitbit.Unit.Tests/Fitbit.Unit.Tests.csproj
    
    dotnet clean ./src/Nokia.Unit.Tests/Nokia.Unit.Tests.csproj
    
    dotnet clean ./src/GoogleSheets.Unit.Tests/GoogleSheets.Unit.Tests.csproj

build:
  project: Health.API.sln
  publish_wap: true
  verbosity: minimal
test: auto
after_test:
- cmd: dotnet publish ./src/HealthAPI /p:OutDir="%appveyor_build_folder%\publish" /p:PackageLocation="%appveyor_build_folder%\publish" /p:PublishProfile=Release /p:WebPublishMethod=Package
artifacts:
- path: publish\*.zip
  name: mypackage
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://musgrosoft-health-api.scm.azurewebsites.net:443/msdeploy.axd?site=Musgrosoft-Health-API
  website: Musgrosoft-Health-API
  username: $Musgrosoft-Health-API
  password:
    secure: +Tef2W21z7HUxOIgJkYgHTkSozAEs7/Eb930gf7mSgGJAxwePhbwAm67F2waTMZPoxiBS/1Kt4VtsQKjlEX0kQ==
  artifact: mypackage
  aspnet_core: true
  remove_files: true
  app_offline: true
  aspnet_core_force_restart: true