drop table BloodPressures
drop table Drinks
drop table Exercises
drop table RestingHeartRates
drop table Targets
drop table Tokens
drop table Weights
drop table CalendarDates
drop table MyWithingsSleeps
drop table MyFitbitSleeps